# Generated by Django 2.1.2 on 2018-11-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '0003_auto_20181110_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('hobbyName', models.CharField(max_length=10)),
                ('hobbyInfo', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('profilePic', models.ImageField(upload_to='profile_images')),
                ('hobbies', models.ManyToManyField(to='MainApp.Hobby')),
            ],
        ),
    ]
