# Generated by Django 2.1.2 on 2018-11-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20181111_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hobbies',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
